### ISSUE TITLE
Class 'Contao\CoreBundle\Controller\FrontendController' not found

### ISSUE THREAD

**Issue by UB3RL33T** [Kuestenschmiede/con4gis_forum#28]
I've installed con4gis/con4gis_forum 2.0.1 on a Contao installation v3.5.19 via composer.

Now I'm getting thrown a fatal error:
`Fatal error: Class 'Contao\CoreBundle\Controller\FrontendController' not found in /composer/vendor/con4gis/con4gis_api_bundle/src/Controller/ApiController.php on line 22`

Is there any way to fix this?

**Comment by coastforge-mei** [comment]
Yes we know this error. We made the composer.json for Contao 4. You don't neet the API-Bundle with Contao 3. Please remove this from composer.json manually or download con4gis-Core and con4gis-Forum from gitHub and put them into system/module (without composer).
